# OAuth and PKCE Services Configuration

services:
    # PKCE Service for code challenge generation and verification
    wallabag.oauth.pkce_service:
        class: Wallabag\Service\OAuth\PkceService
        autowire: false
        autoconfigure: false
        public: true

    # Override global autowiring for PkceOAuthStorage
    Wallabag\Service\OAuth\PkceOAuthStorage:
        autowire: false
        autoconfigure: false
        arguments:
            - '@fos_oauth_server.client_manager'
            - '@fos_oauth_server.access_token_manager'
            - '@fos_oauth_server.refresh_token_manager'
            - '@fos_oauth_server.auth_code_manager'
            - '@fos_user.user_provider.username_email'
            - '@security.encoder_factory'
            - '@wallabag.oauth.pkce_service'
            - '@request_stack'
        public: true

    # PKCE-enhanced OAuth Storage (replaces the default storage)
    wallabag.oauth.storage:
        alias: Wallabag\Service\OAuth\PkceOAuthStorage
        public: true

    # Override the default OAuth storage with our PKCE-enabled one
    fos_oauth_server.storage:
        alias: wallabag.oauth.storage
        public: true

    # OAuth Authorization Controller
    Wallabag\Controller\Api\OAuthController:
        class: Wallabag\Controller\Api\OAuthController
        arguments:
            - '@wallabag.oauth.pkce_service'
            - '@doctrine.orm.entity_manager'
            - '@Wallabag\Repository\Api\ClientRepository'
        calls:
            - [setContainer, ['@service_container']]
        tags: ['controller.service_arguments']